version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: ./.Docker
      dockerfile: Dockerfile
    container_name: embroidr-app
    volumes:
      - .:/var/www/html
      - ./.Docker/entrypoint.sh:/entrypoint.sh
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - embroidr-net
    entrypoint: /entrypoint.sh    

  # MySQL Database
  mysql:
    image: mysql:8
    container_name: embroidr-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: souvik98
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.Docker/mysql_data:/var/lib/mysql
    networks:
      - embroidr-net

  #PhpMyadmin 
  phpmyadmin:
    image: phpmyadmin
    container_name: embroidr-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 2024M
      MEMORY_LIMIT: 512M
    ports:
      - "8081:80"
    networks:
      - embroidr-net  
  #Nginx Reverse Proxy      
  nginx:
    image: nginx
    container_name: embroidr-nginx
    ports:  
      - "80:80"
      - "443:443"
    volumes:
      - ./.Docker/laravel/nginx/conf.d:/etc/nginx/conf.d
      - ./.Docker/laravel/nginx/ssl:/etc/ssl/private
    depends_on:
      - app
      - phpmyadmin
    networks:
      - embroidr-net
networks:
  embroidr-net:
